name: 'conftest-fork'
description: 'Run conftest test command'
inputs:
  path:
    description: 'Path to directory where config files are located'
    required: false
    default: '.'
  policy:
    description: 'Path to the Rego policy files directory'
    required: false
    default: 'policy'
  files:
    description: 'A list of config file to be tested by conftest. Separated by a space'
    required: false
    default: ''
  matches:
    description: 'A list of cases to be tested (e.g. "*.yaml *.json"). Separated by a space'
    required: false
    default: ''
  namespace:
    description: 'Namespace name running with conftest testing'
    required: false
    default: ''
  all_namespaces:
    description: 'Enable --all-namespaces flag'
    required: false
    default: false
outputs:
  result:
    description: 'Outputs of conftest command'
runs:
  using: 'docker'
  image: 'Dockerfile'
